"""change reminder time type

Revision ID: 4e0563422e79
Revises: e8b1f256b3e9
Create Date: 2026-09-28 17:59:02.086831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0563422e79'
down_revision: Union[str, Sequence[str], None] = 'e8b1f256b3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_reminders', 'remind_at',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_reminders', 'remind_at',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
