"""add onboarding fields

Revision ID: 4f01ed6707f4
Revises: a374fc87db29
Create Date: 2026-09-28 16:02:30.089335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f01ed6707f4'
down_revision: Union[str, Sequence[str], None] = 'a374fc87db29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_reminders')
    op.drop_table('books')
    op.drop_table('reading_notes')
    op.drop_table('users')
    op.drop_table('quotes')
    op.drop_table('user_books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('cover_url', sa.VARCHAR(), nullable=False),
    sa.Column('personal_note', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('current_page', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('book_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_book_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=False),
    sa.Column('reading_goal', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_notes',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_book_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('google_books_id', sa.VARCHAR(), nullable=False),
    sa.Column('isbn', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('cover_url', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('publisher', sa.VARCHAR(), nullable=False),
    sa.Column('published_year', sa.INTEGER(), nullable=False),
    sa.Column('genres', sa.VARCHAR(), nullable=False),
    sa.Column('page_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_reminders',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('remind_at', sa.DATETIME(), nullable=False),
    sa.Column('days', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
