"""change reminder time type

Revision ID: e3d96ed3ddf8
Revises: e8b1f256b3e9
Create Date: 2026-09-29 01:49:55.035284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d96ed3ddf8'
down_revision: Union[str, Sequence[str], None] = 'e8b1f256b3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_reminders', schema=None) as batch_op:
        batch_op.alter_column('remind_at',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('days',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_reminders', schema=None) as batch_op:
        batch_op.alter_column('days',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('remind_at',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
